#!/bin/bash
sleep 1 ; echo Comenzara la instalacion del programa
sleep 1 ; echo "Instalaremos Todo lo necesario, Se paciente!"
sleep 3 ; apt-get update -y ; apt-get upgrade -y
sleep 2 ; echo Espera un momento...
sleep 3; Descargando Pacientes
sleep 2 ; wget https://raw.githubusercontent.com/nachorivas581/PROGRAMA/main/ListaPacientes
sleep 2 ; wget https://raw.githubusercontent.com/nachorivas581/PROGRAMA/main/ListaPacientes.txt
sleep 5 ; echo CORRECTO!
sleep 2 ;"Simplificaremos tu trabajo se paciente :) "
sleep 2 ; echo Descargando TURNOS
sleep 2 ; wget https://raw.githubusercontent.com/nachorivas581/PROGRAMA/main/TURNOS
sleep 2 ; wget https://raw.githubusercontent.com/nachorivas581/PROGRAMA/main/TURNOS.txt
sleep 3; echo CORRECTO!
sleep 3; DESCARGANDO PROGRAMA
sleep 2 ;wget https://raw.githubusercontent.com/nachorivas581/PROGRAMA/main/prueba
sleep 3 ; echo CORRECTO!
sleep 2 ; echo YA PUEDES USAR TU PROGRAMA!
