#!/bin/bash
echo -e "\e[32mNombre Y Apellido del paciente:\e[0m"
read Nombre
echo "
$Nombre
-----------------------------------"
echo -e "\e[32mFecha Del Turno:\e[0m"
read Fecha
echo "
$Fecha
----------------------------------"
echo -e "\e[32mHorario Del Turno:\e[0m"
read Horario
echo "
$Horario
-----------------------------------"
echo -e "\e[32mNumero De Contacto:\e[0m"
read social
echo "
$social
-----------------------------------"
